### ISSUE TITLE
On the website, create a table that lists all objects and their properties. When hovering over an entry, it should highlight the related object.

### ISSUE THREAD

**Issue by seveibar** [tscircuit/graphics-debug#2]

**Comment by seveibar** [comment]
/bounty $10

![Image](https://github.com/user-attachments/assets/edd5e170-c06e-409c-813a-1a5eb451771c)

**Comment by kom-senapati** [comment]
/attempt #2 Using getGraphicsObjectsFromLogString to get graphicsObjects and using it to render tables
